FROM openjdk:latest
MAINTAINER Piotr Joński <yoyo@wp.eu>

ARG UPSOURCE_VERSION=3.0.4423 && \
    USER_ID=2000 && \
    USER_NAME=jetbrains
ENV PORT=8080

RUN echo "* - memlock unlimited \n* - nofile 100000 \n* - nproc 32768 \n* - as unlimited" >> /etc/security/limits.conf

RUN groupadd --gid ${USER_ID} ${USER_NAME} && \
    useradd --create-home --home-dir /upsource --uid ${USER_ID} --gid ${USER_NAME} ${USER_NAME} && \
    chown --changes ${USER_NAME}:${USER_NAME} /upsource

USER upsource
WORKDIR /upsource

RUN mkdir backups data logs conf temp && \
    curl -L "http://download.jetbrains.com/upsource/upsource-${UPSOURCE_VERSION}.zip" > upsource.zip && \
    unzip -q upsource.zip && \
    rm -f upsource.zip && \
    mv upsource-${UPSOURCE_VERSION}/* . && \
    rm -rf upsource-${UPSOURCE_VERSION} && \
    rm -rf internal/java/linux-x64/man && \
    rm -rf internal/java/mac-x64 && \
    rm -rf internal/java/windows-amd64

RUN bin/upsource.sh configure \
    --backups-dir ${HOME}/backups \
    --data-dir    ${HOME}/data \
    --logs-dir    ${HOME}/log \
    --temp-dir    ${HOME}/tmp \
    --listen-port ${PORT} \
    --base-url    http://localhost/

EXPOSE ${PORT}
CMD [ "/bin/bash", "/upsource/bin/upsource.sh", "run" ]
