FROM openjdk:latest
MAINTAINER Piotr Joński <yoyo@wp.eu>

ARG HUB_VERSION=2017.1.4205
ENV PORT=8080

RUN mkdir /hub /hub/backups /hub/data /hub/logs /hub/conf /hub/temp
WORKDIR /hub

RUN groupadd --gid 2003 hub && \
    useradd --system -d /hub --uid 2003 --gid hub hub && \
    curl -L "https://download.jetbrains.com/hub/2017.1/hub-ring-bundle-${HUB_VERSION}.zip" > hub.zip && \
    unzip -q hub.zip && \
    rm -f hub.zip && \
    mv hub-ring-bundle-${HUB_VERSION}/* . && \
    rm -rf hub-ring-bundle-${HUB_VERSION} && \
    rm -rf internal/java/linux-x64/man && \
    rm -rf internal/java/mac-x64 && \
    rm -rf internal/java/windows-amd64 && \
    chown -R hub:hub /hub && \
    chmod -R u+rwxX /hub

USER hub
ENV HOME=/hub

RUN bin/hub.sh configure \
    --backups-dir ${HOME}/backups \
    --data-dir    ${HOME}/data \
    --logs-dir    ${HOME}/log \
    --temp-dir    ${HOME}/tmp \
    --listen-port ${PORT} \
    --base-url    http://localhost/

VOLUME ["/hub", "/hub/backups", "/hub/data", "/hub/logs", "/hub/conf", "/hub/temp"]
EXPOSE ${PORT}
CMD [ "/bin/bash", "/hub/bin/hub.sh", "run" ]
